### ISSUE TITLE
Resultado por municipio?

### ISSUE THREAD

**Issue by hermesalvesbr** [OPthyago/eleicoes2022#1]
Amigo ainda nao consegui decifrar como coletar o resultado de deputado estadual por Cidade.

Estou no manual, mas nao tem um URL do json de exemplo para isso. Você tem algum exemplo de Url (json)por municipio? Para o cargo 006 ou 007?

**Comment by OPthyago** [comment]
Oi @hermesalvesbr, não sei te dizer se é possível coletar os dados por cidade.
Pesquisei aqui e não encontrei tal função.

Mas muito obrigado pelo comentário!
